* Added script to re-format Git commit messages to 72 characters * Configuration for Travis continuous integration * Reduced minimum version number for SciPy and Matplotlib to have it   in line with Ubuntu 12. Also modified unit test for figure used in   plot module documentation that produces a slightly different image   with the "downgraded" libraries * Updated unit test for pprint_ast which produces slightly different   results in CI vendor build * Changed way Python version is introspected to make it Python 2.6   friendly * Python 3 compatibility changes in documentation build system * Made setup.py Python 2.6 friendly * misc module: Re-factored test of pprint_ast to make it 3.x friendly * exdoc module:    + Expanded exception catching for files with a null character    + Added in_callables_fname and out_callables_fname to ExDocCxt      context manager so as to use previously-traced module information      and to save information of traced module, respectively * eng module:    + Added no_exp function to return a string representation of a      number that is guaranteed not to be in scientific notation    + Documentation update * exh module:    + Removed all intra-module dependencies other than pinspect so as to      avoid loading dependency hell    + Added option to load traced modules information to ExhHandle class      or get_or_create_exh_obj using the new functionality added to the      pinspect.Callables class * pcontracts module: moved documentation to documentation file because   ReadTheDocs does not capture docstring for contract and new_contract   functions * pinspect module:    + Made module tracing more robust and compatible with      all Python versions, in the process fixed bug that was not properly      closing callables in Python 3.3    + Added load and save methods to Callable class, which load and      retrieve the state of the object to/from a JSON file    + Added refresh method to Callables clss to re-trace modules that have      been modified since the last time they were traced. Refreshed      modules do not  need to be imported. * plot module: made some image comparisons more robust * test module: added descriptive method when exception is not raised   in assert_exception function * tox.ini: Added Python 2.6 to the package validation tests * README.rst Added code of conduct mention * Other Python 2.6 compatibility changes * Added Python 3.5 to package validation * ReadTheDocs build fixes to avoid importing numpy, scipy and   matplotlib modules * Updated trace modules to use new argument name for pickle file * Made mode exception tracing modules homogeneous * Exception documentation use saved traced modules information   (if present) * Added six to the requirements so that plot.DataSource can be a   single function for Python 2 and Python 3, thus fixing ReadTheDocs   build, or in general Python 2 package installation where the sub-   module data_source3.py is byte-compiled and produces a syntax error   when it reaches the class definition line, where the meta-class is   defined * check_file_compliance.py script:    + Check for aspell presence    + More robust recognition for Pylint command * build-docs.sh script: Added pcontracts.rst to file insertion loop * Reformatted some convenience scripts to cap line length to 80   characters * Renamed all Python convenience scripts that had dashes to underscores   so that they could be imported as modules * Removed unused convenience scripts * Initial commit of the build_wheel_cache.py convenience script to   build the wheel cache of all the dependencies thus speeding up   the (re)creation of tox environments

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -35,7 +35,7 @@ if [ "$allownonascii" != "true" ] &&
 	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
 	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
+Error: attempt to add a non-ASCII file name.
 
 This can cause problems if you want to work with people on other platforms.
 
@@ -88,15 +88,18 @@ fi
 ###
 #echo -e "\tValidating author name and email"
 # Check that e-mail and name match the e-mail and address of first commit
-check_email=1
+check_email=0
 first_commit_hash=$(git rev-list --max-parents=0 HEAD)
 history_name=$(git log ${first_commit_hash} --format="%an" | head -n 1)
 history_email=$(git log ${first_commit_hash} --format="%ae" | head -n 1)
 current_name=$(git config --global user.name)
 current_email=$(git config --global user.email)
 if [ "${check_email}" == 1 ]; then
-	if [ "${history_name}" != "${current_name}" ] || [ "${history_email}" != "${current_email}" ]; then
-		echo -e "Error: Incongruent author information, current is ${current_name} <${current_email}>,\nfirst commit is ${history_name} <${history_email}>."
+	if [ "${history_name}" != "${current_name}" ] || \
+		[ "${history_email}" != "${current_email}" ]; then
+		echo -e "Error: incongruent commit author information"
+		echo -e "    Current is ${current_name} <${current_email}>"
+		echo -e "    First is ${history_name} <${history_email}>"
 		exit 1
 	fi
 fi
@@ -106,7 +109,7 @@ fi
 ###
 files=$(git diff --name-only --cached)
 pkg_dir=$(git rev-parse --show-toplevel)
-if ! ${pkg_dir}/sbin/check-files-compliance.py --quiet --aspell --header --pylint "${files}"; then
-	echo -e "Error: Files do not comply with package code standard"
+if ! ${pkg_dir}/sbin/check_files_compliance.py -qstp "${files}"; then
+	echo -e "Error: files do not comply with package code standard"
 	exit 1
 fi
